/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package shop.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

import shop.model.ElectronicsEmployee;

import shop.service.ElectronicsEmployeeLocalService;
import shop.service.ElectronicsEmployeeLocalServiceUtil;
import shop.service.persistence.ElectronicsEmployeePK;
import shop.service.persistence.ElectronicsEmployeePersistence;
import shop.service.persistence.ElectronicsPersistence;
import shop.service.persistence.ElectronicsTypePersistence;
import shop.service.persistence.EmployeeFinder;
import shop.service.persistence.EmployeePersistence;
import shop.service.persistence.PositionTypePersistence;
import shop.service.persistence.PurchaseFinder;
import shop.service.persistence.PurchasePersistence;
import shop.service.persistence.purchaseTypePersistence;

/**
 * Provides the base implementation for the electronics employee local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link shop.service.impl.ElectronicsEmployeeLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see shop.service.impl.ElectronicsEmployeeLocalServiceImpl
 * @generated
 */
public abstract class ElectronicsEmployeeLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, ElectronicsEmployeeLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>ElectronicsEmployeeLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>ElectronicsEmployeeLocalServiceUtil</code>.
	 */

	/**
	 * Adds the electronics employee to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ElectronicsEmployeeLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param electronicsEmployee the electronics employee
	 * @return the electronics employee that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ElectronicsEmployee addElectronicsEmployee(
		ElectronicsEmployee electronicsEmployee) {

		electronicsEmployee.setNew(true);

		return electronicsEmployeePersistence.update(electronicsEmployee);
	}

	/**
	 * Creates a new electronics employee with the primary key. Does not add the electronics employee to the database.
	 *
	 * @param electronicsEmployeePK the primary key for the new electronics employee
	 * @return the new electronics employee
	 */
	@Override
	@Transactional(enabled = false)
	public ElectronicsEmployee createElectronicsEmployee(
		ElectronicsEmployeePK electronicsEmployeePK) {

		return electronicsEmployeePersistence.create(electronicsEmployeePK);
	}

	/**
	 * Deletes the electronics employee with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ElectronicsEmployeeLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param electronicsEmployeePK the primary key of the electronics employee
	 * @return the electronics employee that was removed
	 * @throws PortalException if a electronics employee with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ElectronicsEmployee deleteElectronicsEmployee(
			ElectronicsEmployeePK electronicsEmployeePK)
		throws PortalException {

		return electronicsEmployeePersistence.remove(electronicsEmployeePK);
	}

	/**
	 * Deletes the electronics employee from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ElectronicsEmployeeLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param electronicsEmployee the electronics employee
	 * @return the electronics employee that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ElectronicsEmployee deleteElectronicsEmployee(
		ElectronicsEmployee electronicsEmployee) {

		return electronicsEmployeePersistence.remove(electronicsEmployee);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			ElectronicsEmployee.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return electronicsEmployeePersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>shop.model.impl.ElectronicsEmployeeModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return electronicsEmployeePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>shop.model.impl.ElectronicsEmployeeModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return electronicsEmployeePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return electronicsEmployeePersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return electronicsEmployeePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public ElectronicsEmployee fetchElectronicsEmployee(
		ElectronicsEmployeePK electronicsEmployeePK) {

		return electronicsEmployeePersistence.fetchByPrimaryKey(
			electronicsEmployeePK);
	}

	/**
	 * Returns the electronics employee with the primary key.
	 *
	 * @param electronicsEmployeePK the primary key of the electronics employee
	 * @return the electronics employee
	 * @throws PortalException if a electronics employee with the primary key could not be found
	 */
	@Override
	public ElectronicsEmployee getElectronicsEmployee(
			ElectronicsEmployeePK electronicsEmployeePK)
		throws PortalException {

		return electronicsEmployeePersistence.findByPrimaryKey(
			electronicsEmployeePK);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			electronicsEmployeeLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ElectronicsEmployee.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"primaryKey.employeeId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			electronicsEmployeeLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			ElectronicsEmployee.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"primaryKey.employeeId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			electronicsEmployeeLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ElectronicsEmployee.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"primaryKey.employeeId");
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return electronicsEmployeePersistence.create(
			(ElectronicsEmployeePK)primaryKeyObj);
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return electronicsEmployeeLocalService.deleteElectronicsEmployee(
			(ElectronicsEmployee)persistedModel);
	}

	public BasePersistence<ElectronicsEmployee> getBasePersistence() {
		return electronicsEmployeePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return electronicsEmployeePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the electronics employees.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>shop.model.impl.ElectronicsEmployeeModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of electronics employees
	 * @param end the upper bound of the range of electronics employees (not inclusive)
	 * @return the range of electronics employees
	 */
	@Override
	public List<ElectronicsEmployee> getElectronicsEmployees(
		int start, int end) {

		return electronicsEmployeePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of electronics employees.
	 *
	 * @return the number of electronics employees
	 */
	@Override
	public int getElectronicsEmployeesCount() {
		return electronicsEmployeePersistence.countAll();
	}

	/**
	 * Updates the electronics employee in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ElectronicsEmployeeLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param electronicsEmployee the electronics employee
	 * @return the electronics employee that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ElectronicsEmployee updateElectronicsEmployee(
		ElectronicsEmployee electronicsEmployee) {

		return electronicsEmployeePersistence.update(electronicsEmployee);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			ElectronicsEmployeeLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		electronicsEmployeeLocalService =
			(ElectronicsEmployeeLocalService)aopProxy;

		_setLocalServiceUtilService(electronicsEmployeeLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ElectronicsEmployeeLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ElectronicsEmployee.class;
	}

	protected String getModelClassName() {
		return ElectronicsEmployee.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				electronicsEmployeePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		ElectronicsEmployeeLocalService electronicsEmployeeLocalService) {

		try {
			Field field =
				ElectronicsEmployeeLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, electronicsEmployeeLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected ElectronicsPersistence electronicsPersistence;

	protected ElectronicsEmployeeLocalService electronicsEmployeeLocalService;

	@Reference
	protected ElectronicsEmployeePersistence electronicsEmployeePersistence;

	@Reference
	protected ElectronicsTypePersistence electronicsTypePersistence;

	@Reference
	protected EmployeePersistence employeePersistence;

	@Reference
	protected EmployeeFinder employeeFinder;

	@Reference
	protected PositionTypePersistence positionTypePersistence;

	@Reference
	protected PurchasePersistence purchasePersistence;

	@Reference
	protected PurchaseFinder purchaseFinder;

	@Reference
	protected purchaseTypePersistence purchaseTypePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		ElectronicsEmployeeLocalServiceBaseImpl.class);

}