/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package shop.model.impl;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import shop.model.ElectronicsEmployee;
import shop.model.ElectronicsEmployeeModel;
import shop.model.ElectronicsEmployeeSoap;

import shop.service.persistence.ElectronicsEmployeePK;

/**
 * The base model implementation for the ElectronicsEmployee service. Represents a row in the &quot;shop_ElectronicsEmployee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ElectronicsEmployeeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ElectronicsEmployeeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ElectronicsEmployeeImpl
 * @generated
 */
@JSON(strict = true)
public class ElectronicsEmployeeModelImpl
	extends BaseModelImpl<ElectronicsEmployee>
	implements ElectronicsEmployeeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a electronics employee model instance should use the <code>ElectronicsEmployee</code> interface instead.
	 */
	public static final String TABLE_NAME = "shop_ElectronicsEmployee";

	public static final Object[][] TABLE_COLUMNS = {
		{"employeeId", Types.BIGINT}, {"electronicsTypeId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("electronicsTypeId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table shop_ElectronicsEmployee (employeeId LONG not null,electronicsTypeId LONG not null,primary key (employeeId, electronicsTypeId))";

	public static final String TABLE_SQL_DROP =
		"drop table shop_ElectronicsEmployee";

	public static final String ORDER_BY_JPQL =
		" ORDER BY electronicsEmployee.id.employeeId ASC, electronicsEmployee.id.electronicsTypeId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY shop_ElectronicsEmployee.employeeId ASC, shop_ElectronicsEmployee.electronicsTypeId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMPLOYEEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ELECTRONICSTYPEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static ElectronicsEmployee toModel(
		ElectronicsEmployeeSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		ElectronicsEmployee model = new ElectronicsEmployeeImpl();

		model.setEmployeeId(soapModel.getEmployeeId());
		model.setElectronicsTypeId(soapModel.getElectronicsTypeId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<ElectronicsEmployee> toModels(
		ElectronicsEmployeeSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<ElectronicsEmployee> models = new ArrayList<ElectronicsEmployee>(
			soapModels.length);

		for (ElectronicsEmployeeSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public ElectronicsEmployeeModelImpl() {
	}

	@Override
	public ElectronicsEmployeePK getPrimaryKey() {
		return new ElectronicsEmployeePK(_employeeId, _electronicsTypeId);
	}

	@Override
	public void setPrimaryKey(ElectronicsEmployeePK primaryKey) {
		setEmployeeId(primaryKey.employeeId);
		setElectronicsTypeId(primaryKey.electronicsTypeId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new ElectronicsEmployeePK(_employeeId, _electronicsTypeId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((ElectronicsEmployeePK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return ElectronicsEmployee.class;
	}

	@Override
	public String getModelClassName() {
		return ElectronicsEmployee.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ElectronicsEmployee, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ElectronicsEmployee, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ElectronicsEmployee, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ElectronicsEmployee)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ElectronicsEmployee, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ElectronicsEmployee, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ElectronicsEmployee)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ElectronicsEmployee, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ElectronicsEmployee, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ElectronicsEmployee, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ElectronicsEmployee, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ElectronicsEmployee, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ElectronicsEmployee, Object>>();
		Map<String, BiConsumer<ElectronicsEmployee, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<ElectronicsEmployee, ?>>();

		attributeGetterFunctions.put(
			"employeeId", ElectronicsEmployee::getEmployeeId);
		attributeSetterBiConsumers.put(
			"employeeId",
			(BiConsumer<ElectronicsEmployee, Long>)
				ElectronicsEmployee::setEmployeeId);
		attributeGetterFunctions.put(
			"electronicsTypeId", ElectronicsEmployee::getElectronicsTypeId);
		attributeSetterBiConsumers.put(
			"electronicsTypeId",
			(BiConsumer<ElectronicsEmployee, Long>)
				ElectronicsEmployee::setElectronicsTypeId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	@JSON
	@Override
	public long getElectronicsTypeId() {
		return _electronicsTypeId;
	}

	@Override
	public void setElectronicsTypeId(long electronicsTypeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_electronicsTypeId = electronicsTypeId;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ElectronicsEmployee toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ElectronicsEmployee>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ElectronicsEmployeeImpl electronicsEmployeeImpl =
			new ElectronicsEmployeeImpl();

		electronicsEmployeeImpl.setEmployeeId(getEmployeeId());
		electronicsEmployeeImpl.setElectronicsTypeId(getElectronicsTypeId());

		electronicsEmployeeImpl.resetOriginalValues();

		return electronicsEmployeeImpl;
	}

	@Override
	public int compareTo(ElectronicsEmployee electronicsEmployee) {
		ElectronicsEmployeePK primaryKey = electronicsEmployee.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ElectronicsEmployee)) {
			return false;
		}

		ElectronicsEmployee electronicsEmployee = (ElectronicsEmployee)object;

		ElectronicsEmployeePK primaryKey = electronicsEmployee.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ElectronicsEmployee> toCacheModel() {
		ElectronicsEmployeeCacheModel electronicsEmployeeCacheModel =
			new ElectronicsEmployeeCacheModel();

		electronicsEmployeeCacheModel.electronicsEmployeePK = getPrimaryKey();

		electronicsEmployeeCacheModel.employeeId = getEmployeeId();

		electronicsEmployeeCacheModel.electronicsTypeId =
			getElectronicsTypeId();

		return electronicsEmployeeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ElectronicsEmployee, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ElectronicsEmployee, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ElectronicsEmployee, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ElectronicsEmployee)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ElectronicsEmployee, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ElectronicsEmployee, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ElectronicsEmployee, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ElectronicsEmployee)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ElectronicsEmployee>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ElectronicsEmployee.class, ModelWrapper.class);

	}

	private long _employeeId;
	private long _electronicsTypeId;

	public <T> T getColumnValue(String columnName) {
		Function<ElectronicsEmployee, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ElectronicsEmployee)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("employeeId", _employeeId);
		_columnOriginalValues.put("electronicsTypeId", _electronicsTypeId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("employeeId", 1L);

		columnBitmasks.put("electronicsTypeId", 2L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ElectronicsEmployee _escapedModel;

}