/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package shop.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

import shop.service.persistence.ElectronicsEmployeePK;

/**
 * The base model interface for the ElectronicsEmployee service. Represents a row in the &quot;shop_ElectronicsEmployee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>shop.model.impl.ElectronicsEmployeeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>shop.model.impl.ElectronicsEmployeeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ElectronicsEmployee
 * @generated
 */
@ProviderType
public interface ElectronicsEmployeeModel
	extends BaseModel<ElectronicsEmployee> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a electronics employee model instance should use the {@link ElectronicsEmployee} interface instead.
	 */

	/**
	 * Returns the primary key of this electronics employee.
	 *
	 * @return the primary key of this electronics employee
	 */
	public ElectronicsEmployeePK getPrimaryKey();

	/**
	 * Sets the primary key of this electronics employee.
	 *
	 * @param primaryKey the primary key of this electronics employee
	 */
	public void setPrimaryKey(ElectronicsEmployeePK primaryKey);

	/**
	 * Returns the employee ID of this electronics employee.
	 *
	 * @return the employee ID of this electronics employee
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this electronics employee.
	 *
	 * @param employeeId the employee ID of this electronics employee
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the electronics type ID of this electronics employee.
	 *
	 * @return the electronics type ID of this electronics employee
	 */
	public long getElectronicsTypeId();

	/**
	 * Sets the electronics type ID of this electronics employee.
	 *
	 * @param electronicsTypeId the electronics type ID of this electronics employee
	 */
	public void setElectronicsTypeId(long electronicsTypeId);

}