/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package shop.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Electronics service. Represents a row in the &quot;shop_Electronics&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>shop.model.impl.ElectronicsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>shop.model.impl.ElectronicsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Electronics
 * @generated
 */
@ProviderType
public interface ElectronicsModel extends BaseModel<Electronics> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a electronics model instance should use the {@link Electronics} interface instead.
	 */

	/**
	 * Returns the primary key of this electronics.
	 *
	 * @return the primary key of this electronics
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this electronics.
	 *
	 * @param primaryKey the primary key of this electronics
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the electronics ID of this electronics.
	 *
	 * @return the electronics ID of this electronics
	 */
	public long getElectronicsId();

	/**
	 * Sets the electronics ID of this electronics.
	 *
	 * @param electronicsId the electronics ID of this electronics
	 */
	public void setElectronicsId(long electronicsId);

	/**
	 * Returns the name of this electronics.
	 *
	 * @return the name of this electronics
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this electronics.
	 *
	 * @param name the name of this electronics
	 */
	public void setName(String name);

	/**
	 * Returns the type ID of this electronics.
	 *
	 * @return the type ID of this electronics
	 */
	public long getTypeId();

	/**
	 * Sets the type ID of this electronics.
	 *
	 * @param typeId the type ID of this electronics
	 */
	public void setTypeId(long typeId);

	/**
	 * Returns the price of this electronics.
	 *
	 * @return the price of this electronics
	 */
	public long getPrice();

	/**
	 * Sets the price of this electronics.
	 *
	 * @param price the price of this electronics
	 */
	public void setPrice(long price);

	/**
	 * Returns the count of this electronics.
	 *
	 * @return the count of this electronics
	 */
	public int getCount();

	/**
	 * Sets the count of this electronics.
	 *
	 * @param count the count of this electronics
	 */
	public void setCount(int count);

	/**
	 * Returns the in stock of this electronics.
	 *
	 * @return the in stock of this electronics
	 */
	public boolean getInStock();

	/**
	 * Returns <code>true</code> if this electronics is in stock.
	 *
	 * @return <code>true</code> if this electronics is in stock; <code>false</code> otherwise
	 */
	public boolean isInStock();

	/**
	 * Sets whether this electronics is in stock.
	 *
	 * @param inStock the in stock of this electronics
	 */
	public void setInStock(boolean inStock);

	/**
	 * Returns the archived of this electronics.
	 *
	 * @return the archived of this electronics
	 */
	public boolean getArchived();

	/**
	 * Returns <code>true</code> if this electronics is archived.
	 *
	 * @return <code>true</code> if this electronics is archived; <code>false</code> otherwise
	 */
	public boolean isArchived();

	/**
	 * Sets whether this electronics is archived.
	 *
	 * @param archived the archived of this electronics
	 */
	public void setArchived(boolean archived);

	/**
	 * Returns the description of this electronics.
	 *
	 * @return the description of this electronics
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this electronics.
	 *
	 * @param description the description of this electronics
	 */
	public void setDescription(String description);

}